[project]
name = "linceml"
version = "0.1.0" # Atualizado dinamicamente pelo python-semantic-release
description = "Arquitetura Cross-Engine para Observabilidade de Modelos de Machine Learning"
authors = [{ name = "Gabriel Camelo", email = "gabrielcamelo.dev@gmail.com" }]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pyspark>=3.3.0",
    "polars>=0.20.0",
    "pydantic>=2.5.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
    "behave>=1.2.6",
    "ruff>=0.3.0",
    "mkdocs-material",
    "python-semantic-release>=8.7.0", # Adicionado para garantir compatibilidade local
    "build>=1.0.3"                    # Necessário para o build_command
]

# ------------------------------------------------------------------------------
# Configurações de Versionamento Contínuo (Semantic Release)
# ------------------------------------------------------------------------------
[tool.semantic_release]
version_variables = [
    "src/linceml/__init__.py:__version__",
]
version_toml = [
    "pyproject.toml:project.version",
]
branch = "main"
upload_to_pypi = false
upload_to_release = true
build_command = "pip install build && python -m build"

# Configuração para subversionamento (Pre-releases)
[tool.semantic_release.branches.develop]
match = "develop"
prerelease = true
prerelease_token = "dev"

# ------------------------------------------------------------------------------
# Configurações do Linter e Formatter (Ruff)
# ------------------------------------------------------------------------------
[tool.ruff]
line-length = 100
target-version = "py39"
# Exclui pastas comuns que não devem ser analisadas
exclude = [
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "venv",
    "build",
    "dist",
]

[tool.ruff.lint]
# Seleção de regras para o LinceML
select = [
    "E",   # pycodestyle errors (PEP 8)
    "W",   # pycodestyle warnings
    "F",   # pyflakes (Variáveis não usadas, imports inválidos)
    "I",   # isort (Ordenação alfabética de imports)
    "N",   # pep8-naming (Padrão de nomenclatura de classes/variáveis)
    "D",   # pydocstyle (Garante que tudo tem docstring)
]

ignore = [
    "ANN101", # Ignora a exigência de tipar o "self" em métodos de classe
    "ANN102", # Ignora a exigência de tipar o "cls" em @classmethod
    "D100",   # Opcional: Ignora a obrigatoriedade de docstring no topo de todo arquivo (módulo)
    "D104",   # Opcional: Ignora a obrigatoriedade de docstring em arquivos __init__.py
]

# Configura o validador de docstrings para o padrão Google (Exigência do TCC)
[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
